gridWidth     = 20
gridHeight    = 20
speed         = 125
screenWidth   = 400
screenHeight  = 400
snakeTextures = "sprites/snakes/"
appleTextures = "sprites/fruits/"
fontTexture   = "sprites/font.bmp"
appleNumber   = 1